/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import metier.Chemin;
import metier.PhotoVip;

/**
 *
 * @author p1406759
 */
public class FenetreSaisiePhotoVip extends javax.swing.JDialog {

    /**
     * Creates new form FenetreSaisiePhotoVip
     */
     private PhotoVip laPhotoVip;
    private boolean etatSortie;
    Chemin ch;

    public FenetreSaisiePhotoVip(java.awt.Frame parent, PhotoVip laPhotoVip, Chemin ch) {
        super(parent, true);  // mode modal       
        this.laPhotoVip = laPhotoVip;
        this.ch = ch;
        etatSortie = false;
        initComponents();
    }
    
//     public String getChemin_src() {
//        return chemin_src;
//    }
//
//    public void setChemin_src(String chemin_src) {
//        this.chemin_src = chemin_src;
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txPhotoVip = new javax.swing.JTextField();
        btParcourirPhotoVip = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txLieuPhotoVip = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txDatePhotoVip = new com.toedter.calendar.JDateChooser();
        btValiderPhotoVip = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel5.setText("photo :");

        txPhotoVip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txPhotoVipActionPerformed(evt);
            }
        });

        btParcourirPhotoVip.setText("Parcourir ...");
        btParcourirPhotoVip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btParcourirPhotoVipActionPerformed(evt);
            }
        });

        jLabel3.setText("Lieu :");

        txLieuPhotoVip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txLieuPhotoVipActionPerformed(evt);
            }
        });

        jLabel4.setText("Date : ");

        txDatePhotoVip.setDateFormatString("d-MM-yyyy");

        btValiderPhotoVip.setText("valider");
        btValiderPhotoVip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btValiderPhotoVipActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txLieuPhotoVip, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(btValiderPhotoVip))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txPhotoVip, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btParcourirPhotoVip, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txDatePhotoVip, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txPhotoVip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(btParcourirPhotoVip, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txDatePhotoVip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txLieuPhotoVip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(btValiderPhotoVip)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txPhotoVipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txPhotoVipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txPhotoVipActionPerformed

    private void btParcourirPhotoVipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btParcourirPhotoVipActionPerformed
        // TODO add your handling code here:
        JFileChooser choix = new JFileChooser();
       
        choix.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int retour =choix.showOpenDialog(this);
        ch.setChemin_dest("/public_html/");
        if (retour == JFileChooser.APPROVE_OPTION) {
            choix.getSelectedFile();
            String chemin_src=choix.getSelectedFile().getAbsolutePath(); 
            ch.setChemin_src(chemin_src);

            txPhotoVip.setText(choix.getSelectedFile().getName());
            
        }
        
    }//GEN-LAST:event_btParcourirPhotoVipActionPerformed

   

  
    private void txLieuPhotoVipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txLieuPhotoVipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txLieuPhotoVipActionPerformed

    private void btValiderPhotoVipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btValiderPhotoVipActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        try {
            
            
//            vip.setNomVip(txNom.getText());
            if (txPhotoVip.getText().isEmpty()) {
                throw new Exception("champ lieu de naissance vide");
            }
//            laPhotoVip.setLieu(txPhotoVip.getText());
            
            if (txDatePhotoVip.getDate()==null) {
                throw new Exception("champ date de naissance vide");
            }
            laPhotoVip.setDate(Date.valueOf(format.format(txDatePhotoVip.getDate())));
            
            if (txLieuPhotoVip.getText().isEmpty()) {
                throw new Exception("champ lieu de naissance vide");
            }
            laPhotoVip.setLieu(txLieuPhotoVip.getText());
          
            etatSortie = true;
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erreur", JOptionPane.WARNING_MESSAGE);
        }
        

    }//GEN-LAST:event_btValiderPhotoVipActionPerformed

    public void doFalse() {
        etatSortie=false;
    }
            
    public boolean doModal() {
        setVisible(true);
        return etatSortie;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btParcourirPhotoVip;
    private javax.swing.JButton btValiderPhotoVip;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private com.toedter.calendar.JDateChooser txDatePhotoVip;
    private javax.swing.JTextField txLieuPhotoVip;
    private javax.swing.JTextField txPhotoVip;
    // End of variables declaration//GEN-END:variables
}
