/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import metier.VIP;

/**
 *
 * @author P1406759
 */
public class FenetreModifierVIP extends javax.swing.JDialog {

    /**
     * Creates new form FenetreModifierVIP
     */
    private VIP vip;
    private boolean etatSortie;
    
    public FenetreModifierVIP(java.awt.Frame parent, VIP vip) {
        super(parent, true);
        this.vip = vip;
        etatSortie = false;
        initComponents();
        txNomModif.setText(vip.getNomVip());
        txPrenomModif.setText(vip.getPrenomVip());
        //jcboxCiviliteModif.setText(vip.getElementAt(int i)());
        if(vip.getCivilite().compareTo("M")==0){
            
            jcboxCiviliteModif.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M", "Mme"}));
            
        }else{
            
             jcboxCiviliteModif.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mme", "M"}));
        }
        txDateNaissanceModif.setDate(vip.getDateNaissance());
        txLieuNaissanceModif.setText(vip.getLieuNaissance());
        //jcboxRoleModif.setText(vip.setCodeRole());
//        System.out.print(vip.getCodeRole());
        if(vip.getCodeRole().compareTo("Acteur")==0){
            
            jcboxRoleModif.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Acteur", "Realisateur", "Acteur/Realisateur"}));
            
        }else{
            if(vip.getCodeRole().compareTo("Realisateur")==0){
            
            jcboxRoleModif.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Realisateur", "Acteur", "Acteur/Realisateur"}));
            
            }else{
            
             jcboxRoleModif.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Acteur/Realisateur", "Acteur", "Realisateur"}));
             
            }
        }
        txPaysModif.setText(vip.getNomPays());
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txPrenomModif = new javax.swing.JTextField();
        lbRoleModif = new javax.swing.JLabel();
        lbPaysModif = new javax.swing.JLabel();
        txNomModif = new javax.swing.JTextField();
        txPaysModif = new javax.swing.JTextField();
        lbNomVipModif = new javax.swing.JLabel();
        lbPrenomModif = new javax.swing.JLabel();
        jcboxCiviliteModif = new javax.swing.JComboBox();
        jcboxRoleModif = new javax.swing.JComboBox();
        lbCiviliteModif = new javax.swing.JLabel();
        txDateNaissanceModif = new com.toedter.calendar.JDateChooser();
        lbDateNaissanceModif = new javax.swing.JLabel();
        lbLieuNaissanceModif = new javax.swing.JLabel();
        txLieuNaissanceModif = new javax.swing.JTextField();
        btValid = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbRoleModif.setText("Code Role");

        lbPaysModif.setText("Nom Pays");

        txNomModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNomModifActionPerformed(evt);
            }
        });

        lbNomVipModif.setText("Nom VIP");

        lbPrenomModif.setText("Prenom VIP");

        jcboxCiviliteModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboxCiviliteModifActionPerformed(evt);
            }
        });

        jcboxRoleModif.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Acteur", "Realisateur", "Acteur/Realisateur" }));

        lbCiviliteModif.setText("Civilité");

        txDateNaissanceModif.setDateFormatString("d-MM-yyyy");

        lbDateNaissanceModif.setText("Date de Naissance");

        lbLieuNaissanceModif.setText("Lieu de Naissance");

        btValid.setText("Valider");
        btValid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btValidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lbPrenomModif, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(58, 58, 58)
                                    .addComponent(txPrenomModif, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbNomVipModif, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(58, 58, 58)
                                    .addComponent(txNomModif, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(lbDateNaissanceModif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(26, 26, 26))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbCiviliteModif, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(58, 58, 58)))
                                    .addComponent(jcboxCiviliteModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbLieuNaissanceModif, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(lbRoleModif, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(58, 58, 58)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jcboxRoleModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txLieuNaissanceModif, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txDateNaissanceModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbPaysModif, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(txPaysModif, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btValid)
                        .addGap(165, 165, 165))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomVipModif)
                    .addComponent(txNomModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txPrenomModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPrenomModif))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCiviliteModif)
                    .addComponent(jcboxCiviliteModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbDateNaissanceModif)
                    .addComponent(txDateNaissanceModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txLieuNaissanceModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLieuNaissanceModif))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRoleModif)
                    .addComponent(jcboxRoleModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txPaysModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPaysModif))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btValid)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btValidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btValidActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        try {
            
            if (txNomModif.getText().isEmpty()) {
                throw new Exception("champ nom vide");
            }
            vip.setNomVip(txNomModif.getText());
            if (txPrenomModif.getText().isEmpty()) {
                throw new Exception("champ prenom vide");
            }
            vip.setPrenomVip(txPrenomModif.getText());

            vip.setCivilite(String.valueOf(jcboxCiviliteModif.getSelectedItem()));
            if (txDateNaissanceModif.getDate()==null) {
                throw new Exception("champ date de naissance vide");
            }
            vip.setDateNaissance(Date.valueOf(format.format(txDateNaissanceModif.getDate())));
            if (txLieuNaissanceModif.getText().isEmpty()) {
                throw new Exception("champ lieu de naissance vide");
            }
            vip.setLieuNaissance(txLieuNaissanceModif.getText());;

            vip.setCodeRole(String.valueOf(jcboxRoleModif.getSelectedItem()));
            if (txPaysModif.getText().isEmpty()) {
                throw new Exception("champ nom pays vide");
            }
            vip.setNomPays(txPaysModif.getText());
            etatSortie = true;
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erreur", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btValidActionPerformed

    private void txNomModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNomModifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNomModifActionPerformed

    private void jcboxCiviliteModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboxCiviliteModifActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jcboxCiviliteModifActionPerformed

  
    public boolean doModal() {
        setVisible(true);
        return etatSortie;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btValid;
    private javax.swing.JComboBox jcboxCiviliteModif;
    private javax.swing.JComboBox jcboxRoleModif;
    private javax.swing.JLabel lbCiviliteModif;
    private javax.swing.JLabel lbDateNaissanceModif;
    private javax.swing.JLabel lbLieuNaissanceModif;
    private javax.swing.JLabel lbNomVipModif;
    private javax.swing.JLabel lbPaysModif;
    private javax.swing.JLabel lbPrenomModif;
    private javax.swing.JLabel lbRoleModif;
    private com.toedter.calendar.JDateChooser txDateNaissanceModif;
    private javax.swing.JTextField txLieuNaissanceModif;
    private javax.swing.JTextField txNomModif;
    private javax.swing.JTextField txPaysModif;
    private javax.swing.JTextField txPrenomModif;
    // End of variables declaration//GEN-END:variables
}
