/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import accesAuxDonnees.FTPUploadfile;
import java.sql.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import metier.Chemin;
import metier.Evenement;
import metier.Film;
import metier.PhotoVip;
import metier.VIP;
import modele.ModelJTableEvenement;
import modele.ModeleJComboBoxGenre;
import modele.ModeleJComboboxPays;
import modele.ModeleJTable;
import modele.ModeleJTableNumVipPhoto;
import modele.ModeleJtablePhotoVip;
import modele.modeleJTableFilm;
import modele.modeleVipEvenement;


public class FenetreApplication extends javax.swing.JFrame {

    private ModeleJTable leModele;
    private ModelJTableEvenement leModeleEvent;
    private modeleJTableFilm leModeleFilm;
    private ModeleJComboBoxGenre leModeleJComboBoxGenre;
    ModeleJComboboxPays leModeleJComboboxPays;
    private ModeleJtablePhotoVip leModeleJtablePhotoVip;
    private ModeleJTableNumVipPhoto leModeleJTableNumVipPhoto;
//    private modeleVipEvenement lemodeleVipEvenement;
//    private modeleVipEvenement lemodeleVipEvenement2;
    String chemin_src;
    Chemin ch;
    String chemin_dest;
    
    

    public FenetreApplication(ModeleJTable leModele, ModelJTableEvenement leModeleEvent, modeleJTableFilm leModeleFilm,ModeleJComboboxPays leModeleJComboboxPays, ModeleJComboBoxGenre leModeleJComboBoxGenre, ModeleJtablePhotoVip leModeleJtablePhotoVip, ModeleJTableNumVipPhoto leModeleJTableNumVipPhoto) {
        this.leModele = leModele;
        this.leModeleEvent = leModeleEvent;
//        this.lemodeleVipEvenement = lemodeleVipEvenement;
//        this.lemodeleVipEvenement2 = lemodeleVipEvenement2;
        this.leModeleFilm = leModeleFilm;
        this.leModeleJComboBoxGenre = leModeleJComboBoxGenre;
        this.leModeleJComboboxPays = leModeleJComboboxPays;
        this.leModeleJtablePhotoVip = leModeleJtablePhotoVip;
        this.leModeleJTableNumVipPhoto = leModeleJTableNumVipPhoto;
        // initialisation
        initComponents();
        // affichage
        try {
            leModele.chargerLesEmployes();
            leModeleEvent.chargerLesEvenements();
//            lemodeleVipEvenement.chargerLesVipsEvent();
            leModeleFilm.chargerLesFilms();
            leModeleJComboBoxGenre.chargerlesGenres();
            leModeleJComboboxPays.chargerLesPays();
            leModeleJtablePhotoVip.chargerLesPhotos();
            leModeleJTableNumVipPhoto.chargerLesVips2();
        } catch (Exception ex) {
            Logger.getLogger(FenetreApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btInserer = new javax.swing.JButton();
        btSupprimer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        laTable = new javax.swing.JTable();
        btmodifier = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        laTableEvent = new javax.swing.JTable();
        btInsererMariage = new javax.swing.JButton();
        btDefaireMariage = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        laTableFillm = new javax.swing.JTable();
        btInsererFilm = new javax.swing.JButton();
        btSupprimerFilm = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        laTablePhotoVip1 = new javax.swing.JTable();
        btInsererPhotoVip = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        laTablePhotoVip = new javax.swing.JTable();
        btSuprimmerPhotoVip = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Affichage des employés");
        setBackground(new java.awt.Color(255, 153, 153));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(204, 0, 0));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VOICELA  ");
        jPanel5.add(jLabel1);
        jLabel1.setBounds(150, 30, 136, 37);

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("application de gestion de VIP");
        jPanel5.add(jLabel2);
        jLabel2.setBounds(170, 70, 208, 27);
        jPanel5.add(jLabel3);
        jLabel3.setBounds(0, 0, 800, 140);

        jTabbedPane1.setToolTipText("");

        btInserer.setText("Inserer");
        btInserer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsererActionPerformed(evt);
            }
        });

        btSupprimer.setText("Supprimer");
        btSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSupprimerActionPerformed(evt);
            }
        });

        laTable.setModel(leModele);
        jScrollPane1.setViewportView(laTable);

        btmodifier.setText("Modifier un VIP");
        btmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmodifierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(btInserer, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(btmodifier, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btInserer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btmodifier, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jTabbedPane1.addTab("VIP", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        laTableEvent.setBackground(new java.awt.Color(204, 255, 255));
        laTableEvent.setModel(leModeleEvent);
        jScrollPane3.setViewportView(laTableEvent);

        btInsererMariage.setText("Inserer un Mariage");
        btInsererMariage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsererMariageActionPerformed(evt);
            }
        });

        btDefaireMariage.setText("Défaire une Union");
        btDefaireMariage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDefaireMariageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(btInsererMariage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 261, Short.MAX_VALUE)
                .addComponent(btDefaireMariage)
                .addGap(116, 116, 116))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btInsererMariage, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDefaireMariage, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("EVENEMENT", jPanel2);

        laTableFillm.setModel(leModeleFilm);
        jScrollPane2.setViewportView(laTableFillm);

        btInsererFilm.setText("Inserer");
        btInsererFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsererFilmActionPerformed(evt);
            }
        });

        btSupprimerFilm.setText("Supprimer");
        btSupprimerFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSupprimerFilmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btInsererFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSupprimerFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSupprimerFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btInsererFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jTabbedPane1.addTab("FILM", jPanel3);

        laTablePhotoVip1.setModel(leModeleJTableNumVipPhoto);
        jScrollPane5.setViewportView(laTablePhotoVip1);

        btInsererPhotoVip.setText("ajouter Photo");
        btInsererPhotoVip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsererPhotoVipActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(btInsererPhotoVip, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btInsererPhotoVip, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );

        laTablePhotoVip.setModel(leModeleJtablePhotoVip);
        jScrollPane4.setViewportView(laTablePhotoVip);

        btSuprimmerPhotoVip.setText("suprimmer");
        btSuprimmerPhotoVip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuprimmerPhotoVipActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(btSuprimmerPhotoVip, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btSuprimmerPhotoVip, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("PHOTO", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSupprimerActionPerformed
        // TODO add your handling code here:
        try {
            int ligne = laTable.getSelectedRow();
            leModele.supprimerEmploye(ligne);
        } catch (Exception e) {
            System.out.println("Exception à la suppression : " + e.getMessage());
        }
    }//GEN-LAST:event_btSupprimerActionPerformed

    private void btInsererActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsererActionPerformed
        // TODO add your handling code here:
        try {
            VIP vip = new VIP();
            FenetreSaisie laSaisie = new FenetreSaisie(this, vip, leModeleJComboboxPays);
//            System.out.print(laSaisie.doModal());
            if (laSaisie.doModal() == true) {
                int numVip = leModele.maxNumVip();
                vip.setNumVip(numVip);
                vip.setCodeStatut("Célibataire");
//                System.out.print("\n\n"+vip);
               leModele.insererEmploye(vip);
            } 
        } catch (Exception e) {
            if(e.toString().contains("nom trigger")){
//            message=
            }
        }
    }//GEN-LAST:event_btInsererActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int reponse = JOptionPane.showConfirmDialog(this, "Voulez vraiment sortir ?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (reponse == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private void btInsererMariageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsererMariageActionPerformed
        // TODO add your handling code here:
        try {
           
            
            Evenement Event= new Evenement();
            FenetreSaisieMariage laSaisie = new FenetreSaisieMariage(this, Event);
            if (laSaisie.doModal() == true) {
                
                leModeleEvent.insererMariage(Event); 
                
            }
            leModeleEvent.clear();
            leModele.chargerLesEmployes();
        } catch (Exception e) {
            System.out.println("Exception à l'insertion : " + e.getMessage());
        }
    }//GEN-LAST:event_btInsererMariageActionPerformed

    private void btDefaireMariageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDefaireMariageActionPerformed
        // TODO add your handling code here:
        try {
            int ligne = laTableEvent.getSelectedRow();
            int numVip1=(int)leModeleEvent.getValueAt(ligne, 0);
            Date dateMariage=(Date)leModeleEvent.getValueAt(ligne,1);
            int numVip2=(int)leModeleEvent.getValueAt(ligne, 2);
            String lieu=(String)leModeleEvent.getValueAt(ligne, 3);          
             Evenement Divorce= new Evenement(numVip1,dateMariage,numVip2,lieu,null);
//             leModeleEvent.clear();
             FenetreSaisieDivorce laSaisie = new FenetreSaisieDivorce(this, Divorce);
            if (laSaisie.doModal() == true) {
                 leModeleEvent.clear();
                 leModele.clear();
                 leModeleEvent.insererDivorce(Divorce);
                 leModeleEvent.chargerLesEvenements(); 
                 leModele.chargerLesEmployes();
                 
                 
            }else{
                leModeleEvent.clear();
                leModeleEvent.chargerLesEvenements();
            }
            
           
        } catch (Exception e) {
            System.out.println("Exception à la suppression : " + e.getMessage());
            
            
        }
    }//GEN-LAST:event_btDefaireMariageActionPerformed

    private void btInsererFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsererFilmActionPerformed
        // TODO add your handling code here:
        try {
            Film film = new Film();
            FenetreSaisieFilm laSaisie = new FenetreSaisieFilm(this, film, leModeleJComboBoxGenre);
            if (laSaisie.doModal() == true) {
               leModeleFilm.insererFilm(film);
            } 
        } catch (Exception e) {
            System.out.println("Exception à l'insertion : " + e.getMessage());
        }
    }//GEN-LAST:event_btInsererFilmActionPerformed

    private void btSupprimerFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSupprimerFilmActionPerformed
        // TODO add your handling code here:
        try {
            int ligne = laTableFillm.getSelectedRow();
            leModeleFilm.supprimerFilm(ligne);
        } catch (Exception e) {
            System.out.println("Exception à la suppression : " + e.getMessage());
        }
    }//GEN-LAST:event_btSupprimerFilmActionPerformed

    private void btmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmodifierActionPerformed
        // TODO add your handling code here:
         try {
            int ligne = laTable.getSelectedRow();
            int numVip=(int)leModele.getValueAt(ligne, 0);
            String nomVip=(String)leModele.getValueAt(ligne, 1);
            String prenomVip=(String)leModele.getValueAt(ligne, 2);
            String civilite=(String)leModele.getValueAt(ligne, 3);
            Date dateNaissance=(Date)leModele.getValueAt(ligne,4);
            String lieuNaissance=(String)leModele.getValueAt(ligne, 5);
            String codeRole=(String)leModele.getValueAt(ligne, 6);
            String nomPays=(String)leModele.getValueAt(ligne, 7);
            String codeStatut=(String)leModele.getValueAt(ligne, 8);
            
            
                    
             VIP newVip= new VIP(numVip,nomVip,prenomVip,civilite,dateNaissance, lieuNaissance, codeRole, nomPays, codeStatut);
             leModele.clear();
             FenetreModifierVIP laSaisieNewVip = new FenetreModifierVIP(this, newVip);         
            if (laSaisieNewVip.doModal() == true) {
                 leModele.modifierVip(newVip);
                 leModele.chargerLesEmployes();
            }else{
                leModele.chargerLesEmployes();
            }
            
           
        } catch (Exception e) {
            System.out.println("Exception à la suppression : " + e.getMessage());
        }
    }//GEN-LAST:event_btmodifierActionPerformed

    private void btSuprimmerPhotoVipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuprimmerPhotoVipActionPerformed
         try {
            int ligne = laTablePhotoVip.getSelectedRow();
            leModeleJtablePhotoVip.supprimerPhotoVip(ligne);
        } catch (Exception e) {
            System.out.println("Exception à la suppression : " + e.getMessage());
        }
    }//GEN-LAST:event_btSuprimmerPhotoVipActionPerformed

    private void btInsererPhotoVipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsererPhotoVipActionPerformed
        // TODO add your handling code here:
        try {
            int ligne = laTablePhotoVip1.getSelectedRow();
            int numVip=(int)leModeleJTableNumVipPhoto.getValueAt(ligne, 0);
            System.out.println("numvip :"+ numVip);
            int numeroSequentid=leModeleJTableNumVipPhoto.maxSequentPhoto(numVip);
//            PhotoVip laPhotoVip = null;
//            System.out.println("numeroSequentid :"+ numeroSequentid);
//            Date date=laPhotoVip.getDate();
//            System.out.println("date :"+ date);
//            String lieu=(String)laPhotoVip.getLieu();
//            System.out.println("lieu :"+ lieu);
              Date date = null;
              String lieu = null;
              Chemin ch= new Chemin();
             PhotoVip laPhotoVip= new PhotoVip(numVip,numeroSequentid,date,lieu);
             System.out.println("laPhotoVip :"+ laPhotoVip);
             leModeleJtablePhotoVip.clear();
            FenetreSaisiePhotoVip laFenetreSaisiePhotoVip = new FenetreSaisiePhotoVip(this,laPhotoVip,ch);         
            if (laFenetreSaisiePhotoVip.doModal() == true) {
                
                String nomfichier=numVip+"-"+numeroSequentid+".jpg";
                
                FTPUploadfile charger= new FTPUploadfile(ch.getChemin_src(),ch.getChemin_dest(),nomfichier);
                    leModeleJtablePhotoVip.insererPhoto(laPhotoVip);
                    laFenetreSaisiePhotoVip.doFalse();
            }
            
           
        } catch (Exception e) {
            System.out.println("Exception à la L'ajout d'une photo : " + e.getMessage());
        }
    }//GEN-LAST:event_btInsererPhotoVipActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDefaireMariage;
    private javax.swing.JButton btInserer;
    private javax.swing.JButton btInsererFilm;
    private javax.swing.JButton btInsererMariage;
    private javax.swing.JButton btInsererPhotoVip;
    private javax.swing.JButton btSupprimer;
    private javax.swing.JButton btSupprimerFilm;
    private javax.swing.JButton btSuprimmerPhotoVip;
    private javax.swing.JButton btmodifier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable laTable;
    private javax.swing.JTable laTableEvent;
    private javax.swing.JTable laTableFillm;
    private javax.swing.JTable laTablePhotoVip;
    private javax.swing.JTable laTablePhotoVip1;
    // End of variables declaration//GEN-END:variables
}
