/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import java.net.PasswordAuthentication;

/**
 *
 * @author Administrateur
 */
public class FenetreIdentification extends javax.swing.JDialog {

    /**
     * Creates new form FenetreIdentification
     * @param parent
     */
    public FenetreIdentification(java.awt.Frame parent) {       
        super(parent, true);
        initComponents();
    }

    public PasswordAuthentication identifier() {
        setVisible(true);
        return new PasswordAuthentication(txUser.getText(), txPasswd.getPassword());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbUser = new javax.swing.JLabel();
        lbPasswd = new javax.swing.JLabel();
        txUser = new javax.swing.JTextField();
        txPasswd = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Identification");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(675, 235));
        setPreferredSize(new java.awt.Dimension(675, 235));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                Fermeture(evt);
            }
        });
        getContentPane().setLayout(null);

        lbUser.setForeground(new java.awt.Color(255, 255, 255));
        lbUser.setText("User");
        getContentPane().add(lbUser);
        lbUser.setBounds(360, 50, 26, 16);

        lbPasswd.setForeground(new java.awt.Color(255, 255, 255));
        lbPasswd.setText("Password");
        getContentPane().add(lbPasswd);
        lbPasswd.setBounds(360, 100, 60, 16);

        txUser.setText("p1406759");
        txUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txUserActionPerformed(evt);
            }
        });
        getContentPane().add(txUser);
        txUser.setBounds(460, 40, 148, 22);

        txPasswd.setText("215036");
        getContentPane().add(txPasswd);
        txPasswd.setBounds(460, 100, 148, 22);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(460, 150, 70, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("VOICELA");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 60, 100, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("application de gestion de VIP");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 90, 190, 40);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\florent\\Documents\\G6S3\\CPOA\\slider.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 670, 190);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Fermeture(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_Fermeture
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Fermeture

    private void txUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txUserActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbPasswd;
    private javax.swing.JLabel lbUser;
    private javax.swing.JPasswordField txPasswd;
    private javax.swing.JTextField txUser;
    // End of variables declaration//GEN-END:variables
}
